In [ ]:
!pip install pandas numpy scikit-learn nltk

In [ ]:
import pandas as pd
import numpy as np

import nltk
nltk.download('stopwords')
nltk.download('punkt')

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving spam.csv to spam.csv


In [ ]:
df = pd.read_csv("spam.csv", encoding='latin-1')
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN


In [ ]:
df = pd.read_csv("spam.csv", encoding='latin-1')

# Keep only required columns
df = df[['v1', 'v2']]

# Rename columns
df.columns = ['label', 'message']

df.head()

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [ ]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')   # ⭐ IMPORTANT (new)
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
def preprocess(text):
    text = text.lower()  # lowercase
    words = word_tokenize(text)  # tokenize

    filtered = []
    for word in words:
        if word.isalnum() and word not in stopwords.words('english'):
            filtered.append(word)

    return " ".join(filtered)

df['message'] = df['message'].apply(preprocess)
df.head()

,label,message
0,ham,go jurong point crazy available bugis n great ...
1,ham,ok lar joking wif u oni
2,spam,free entry 2 wkly comp win fa cup final tkts 2...
3,ham,u dun say early hor u c already say
4,ham,nah think goes usf lives around though


In [ ]:
df['label'] = df['label'].map({'ham': 0, 'spam': 1})
df.head()

,label,message
0,0,go jurong point crazy available bugis n great ...
1,0,ok lar joking wif u oni
2,1,free entry 2 wkly comp win fa cup final tkts 2...
3,0,u dun say early hor u c already say
4,0,nah think goes usf lives around though


In [ ]:
#Split Data
from sklearn.model_selection import train_test_split

X = df['message']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
#TF-IDF Feature Extraction
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [ ]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

lr = LogisticRegression()
lr.fit(X_train_vec, y_train)

y_pred_lr = lr.predict(X_test_vec)

print("1. Logistic Regression")
print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_lr))

1. Logistic Regression
Accuracy: 0.9497757847533632
Confusion Matrix:
 [[960   5]
 [ 51  99]]


In [ ]:
#Naïve Bayes
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()
nb.fit(X_train_vec, y_train)

y_pred_nb = nb.predict(X_test_vec)

print("2. Naive Bayes ")
print("Accuracy:", accuracy_score(y_test, y_pred_nb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_nb))

2. Naive Bayes 
Accuracy: 0.968609865470852
Confusion Matrix:
 [[965   0]
 [ 35 115]]


In [ ]:
#SVM
from sklearn.svm import SVC

svm = SVC()
svm.fit(X_train_vec, y_train)

y_pred_svm = svm.predict(X_test_vec)

print("3. SVM ")
print("Accuracy:", accuracy_score(y_test, y_pred_svm))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_svm))

3. SVM 
Accuracy: 0.9739910313901345
Confusion Matrix:
 [[963   2]
 [ 27 123]]


In [ ]:
#Detailed Evaluation
from sklearn.metrics import classification_report

print(" Classification Report (SVM) ")
print(classification_report(y_test, y_pred_svm))

 Classification Report (SVM) 
              precision    recall  f1-score   support

           0       0.97      1.00      0.99       965
           1       0.98      0.82      0.89       150

    accuracy                           0.97      1115
   macro avg       0.98      0.91      0.94      1115
weighted avg       0.97      0.97      0.97      1115



In [ ]:
# comparison of all models
print("Model Comparison:")
print("Logistic Regression:", accuracy_score(y_test, y_pred_lr))
print("Naive Bayes:", accuracy_score(y_test, y_pred_nb))
print("SVM:", accuracy_score(y_test, y_pred_svm))

Model Comparison:
Logistic Regression: 0.9497757847533632
Naive Bayes: 0.968609865470852
SVM: 0.9739910313901345


In [ ]:
# test
def predict_spam(message):
    processed = preprocess(message)
    vec = vectorizer.transform([processed])
    prediction = svm.predict(vec)[0]
    prob = svm.decision_function(vec)[0]   # confidence score

    print("= RESULT =")
    print("Message:", message)
    print("-----------------------------")

    if prediction == 1:
        print("Prediction: SPAM 🚫")
    else:
        print("Prediction: HAM ✅")

    print("Confidence Score:", round(prob, 2))

predict_spam("Congratulations! You won a free iPhone")
predict_spam("Hey, are you coming to class?")


= RESULT =
Message: Congratulations! You won a free iPhone
-----------------------------
Prediction: SPAM 🚫
Confidence Score: 0.08
= RESULT =
Message: Hey, are you coming to class?
-----------------------------
Prediction: HAM ✅
Confidence Score: -1.26
